---
kind: ConfigMap
apiVersion: v1
metadata:
  name: mdcore-env
data:
  REST_PORT: {{ .Values.MDCORE_REST_PORT | quote }}
  DB_MODE:   {{ .Values.MDCORE_DB_MODE   | quote }}
  DB_TYPE:   {{ .Values.MDCORE_DB_TYPE   | quote }}
  DB_HOST:   {{ .Values.MDCORE_DB_HOST   | quote }}
  DB_PORT:   {{ .Values.MDCORE_DB_PORT   | quote }}
  ACTIVATION_SERVER: {{ .Values.activation_server }}
  CERT_PATH: {{ .Values.MDCORE_CERT_PATH   | quote }}


# Generate, set or keep the postgres database credentials
{{- $postgresPasswordValue := (randAlphaNum 24) | nospace | b64enc | quote }}
{{- $postgresUserValue := "postgres" | b64enc | quote }}
{{- $postgresSecret := (lookup "v1" "Secret" .Release.Namespace "mdcore-postgres-cred") }}
{{- if $postgresSecret }}
{{- $postgresPasswordValue = index $postgresSecret.data "password" }}
{{- $postgresUserValue = index $postgresSecret.data "user" }}
{{- end -}}
{{- if .Values.db_password }}
{{- $postgresPasswordValue = .Values.db_password | b64enc }}
{{- end -}}
{{- if .Values.db_user }}
{{- $postgresUserValue = .Values.db_user | b64enc }}
{{- end }}

---
kind: Secret
apiVersion: v1
metadata:
  name: mdcore-postgres-cred
  annotations:
    "helm.sh/resource-policy": keep
data:
  user: {{ $postgresUserValue }}
  password: {{ $postgresPasswordValue }}



# Generate, set or keep the MD Core credentials
{{- $corePasswordValue := (randAlphaNum 24) | nospace | b64enc | quote }}
{{- $coreUserValue := "admin" | b64enc | quote }}
{{- $coreCredSecret := (lookup "v1" "Secret" .Release.Namespace "mdcore-cred") }}
{{- if $coreCredSecret }}
{{- $corePasswordValue = index $coreCredSecret.data "password" }}
{{- $coreUserValue = index $coreCredSecret.data "user" }}
{{- end -}}
{{- if .Values.mdcore_password }}
{{- $corePasswordValue = .Values.mdcore_password  }}
{{- end -}}
{{- if .Values.mdcore_user }}
{{- $coreUserValue = .Values.mdcore_user | b64enc }}
{{- end }}

---
kind: Secret
apiVersion: v1
metadata:
  name: mdcore-cred
  annotations:
    "helm.sh/resource-policy": keep
data:
  user: {{ $coreUserValue }}
  password: {{ $corePasswordValue }}


# Generate, set or keep the MD Core API key
{{- $coreApiKeyValue := (randNumeric 36) | b64enc | quote }}
{{- $coreApiSecret := (lookup "v1" "Secret" .Release.Namespace "mdcore-api-key") }}
{{- if $coreApiSecret }}
{{- $coreApiKeyValue = index $coreApiSecret.data "value" }}
{{- end -}}
{{- if .Values.mdcore_api_key }}
{{- $coreApiKeyValue = .Values.mdcore_api_key | b64enc }}
{{- end }}

---
kind: Secret
apiVersion: v1
metadata:
  name: mdcore-api-key
  annotations:
    "helm.sh/resource-policy": keep
data:
  value: {{ $coreApiKeyValue }}


# Set or keep the MD Core license key
{{- $coreLicenseKeyValue := "SET_LICENSE_KEY_HERE" | b64enc | quote }}
{{- $coreLicenseSecret := (lookup "v1" "Secret" .Release.Namespace "mdcore-license-key") }}
{{- if $coreLicenseSecret }}
{{- $coreLicenseKeyValue = index $coreLicenseSecret.data "value" }}
{{- end -}}
{{- if .Values.mdcore_license_key }}
{{- $coreLicenseKeyValue = .Values.mdcore_license_key | b64enc }}
{{- end }}

---
kind: Secret
apiVersion: v1
metadata:
  name: mdcore-license-key
  annotations:
    "helm.sh/resource-policy": keep
data:
  value: {{ $coreLicenseKeyValue }}
