
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: mdcore-env
data:
  REST_PORT: {{ .Values.MDCORE_REST_PORT | quote }}
  DB_MODE:   {{ .Values.MDCORE_DB_MODE   | quote }}
  DB_TYPE:   {{ .Values.MDCORE_DB_TYPE   | quote }}
  DB_HOST:   {{ .Values.MDCORE_DB_HOST   | quote }}
  DB_PORT:   {{ .Values.MDCORE_DB_PORT   | quote }}
  ACTIVATION_SERVER: {{ .Values.activation_server }}
  CERT_PATH: {{ .Values.MDCORE_CERT_PATH   | quote }}
---
# add config-map for mdcore-import-zip-config
{{- if and ($.Values.CONFIG_IMPORT_FILE) ($.Values.CONFIG_IMPORT_PASSWORD) }}
kind: ConfigMap
apiVersion: v1
metadata:
  name: mdcore-import-zip-config
data:
  CONFIG_IMPORT_FILE: {{ .Values.CONFIG_IMPORT_FILE | quote }}
  CONFIG_IMPORT_PASSWORD: {{ .Values.CONFIG_IMPORT_PASSWORD | quote }}
{{- end }}

---

{{ if .Values.env }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-config" .Release.Name }}
data:
  {{- range $key, $val := .Values.env }}
  {{ $key }}: {{ $val | quote }}
  {{- end}}
{{ end }}

---