# Create a deployment for each component in MD Core if it's enabled

{{ range $component_name, $component := .Values.core_components }}
{{ if and (or $.Values.deploy_with_core_db (not $component.is_db)) ( or (not $component.module_name) (contains (print $component.module_name) $.Values.ENABLED_MODULES)) }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $component.name | quote }}
spec:
  replicas: {{ $component.replicas }}
  selector:
    matchLabels:
      app: {{ $component.name | quote }}
  {{- if $component.strategy}}
  strategy:
    {{- toYaml $component.strategy | nindent 4 }}
  {{- end }}
  template:
    metadata:
      labels:
        app: {{ $component.name | quote }}
        {{- if $component.extra_labels }}
          {{- toYaml $component.extra_labels | nindent 8 }}
        {{- end }}
    spec:
      containers:
        - envFrom:
            - configMapRef:
                name: mdcore-env
            {{- if $.Values.env }}
            - configMapRef:
                name: {{ printf "%s-config" $.Release.Name }}
            {{- end }}
          {{ if $component.custom_repo -}}
          image: {{ printf "%s/%s:%s" $.Values.core_docker_repo $component.image $.Values.BRANCH | quote }}
          {{- else -}}
          image: {{ $component.image | quote }}
          {{- end }}
          imagePullPolicy: {{ $.Values.imagePullPolicy }}
          {{- if $component.env }}
          env:
            {{- toYaml $component.env | nindent 12 }}
          {{- end }}
          name: {{ $component.name | quote }}
          {{- if $component.ports }}
          ports:
          {{- range $component.ports }}
            - containerPort: {{ .port }}
          {{- end }}
          {{- end }}
          {{- if $component.livenessProbe }}
          livenessProbe:
            {{- toYaml $component.livenessProbe | nindent 12 }}
          {{- end }}
          {{- if $component.startupProbe }}
          startupProbe:
            {{- toYaml $component.startupProbe | nindent 12 }}
          {{- end }}
          {{- if $component.readinessProbe }}
          readinessProbe:
            {{- toYaml $component.readinessProbe | nindent 12 }}
          {{- end }}
          {{- if $component.command }}
          command: 
            {{- toYaml $component.command | nindent 12 }}
          {{- end }}
          {{- if $component.args }}
          args:
            {{- toYaml $component.args | nindent 12 }}
          {{- end }}
          {{- if $component.securityContext }}
          securityContext:
            {{- toYaml $component.securityContext | nindent 12 }}
          {{- end }}
          {{- $tls := default dict $component.tls }}
          {{- if (or $component.mountConfig $tls.enabled $component.persistentDir $component.extraVolumeMounts)}}
          volumeMounts:
            {{- if $component.mountConfig }}
            - name: {{ $component.mountConfig.configName }}
              mountPath: {{ $component.mountConfig.mountPath }}
              subPath: {{ $component.mountConfig.subPath }}
            {{ end }}
            {{- if $tls.enabled }}
            - name: {{ $component.tls.certSecret }}
              mountPath: {{ $.Values.MDCORE_CERT_PATH }}/mdcore.crt
              subPath: {{ $component.tls.certSecretSubPath }}
            - name: {{ $component.tls.certKeySecret }}
              mountPath: {{ $.Values.MDCORE_CERT_PATH }}/mdcore.key
              subPath: {{ $component.tls.certKeySecretSubPath }}
            {{ end }}
            {{- if $component.persistentDir }}
            - name: {{ $component.name }}
              mountPath: {{ $component.persistentDir }}
              {{- if not (eq $.Values.storage_provisioner "hostPath") }}
              subPath: {{ $component.name }}
              {{- end }}
            {{ end }}
            {{- if $component.extraVolumeMounts }}
              {{- toYaml $component.extraVolumeMounts | nindent 12 }}
            {{- end }}
          {{- end }}
          {{- if $component.resources }}
          resources:
            {{- toYaml $component.resources | nindent 12 }}
          {{- end }}
          {{- if $component.sidecars }}
            {{- toYaml $component.sidecars | nindent 8 }}
          {{- end }}
      {{- if $component.initContainers }}
      initContainers:
        {{- toYaml $component.initContainers | nindent 8 }}
      {{- end }}
      restartPolicy: Always
      {{- if $.Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml $.Values.imagePullSecrets | nindent 8 }}
      {{- end }}
      {{- if $component.customPodDefinitions }}
        {{- toYaml $component.customPodDefinitions | nindent 6 }}
      {{- end }}
      {{- if (or $component.mountConfig $tls.enabled $component.persistentDir $component.extraVolumes )}}
      volumes:
        {{- if $component.mountConfig }}
        - name: {{ $component.mountConfig.configName }}
          configMap:
            name: {{ $component.mountConfig.configName }}
        {{ end }} 
        {{- if $tls.enabled }}
        - name: {{ $component.tls.certSecret }}
          secret:
            secretName: {{ $component.tls.certSecret }}
        - name: {{ $component.tls.certKeySecret }}
          secret:
            secretName: {{ $component.tls.certKeySecret }}
        {{ end }}
        {{- if $component.persistentDir }}
        {{- if eq $.Values.storage_provisioner "hostPath" }}
        - name: {{ $component.name }}
          hostPath:
            path: {{ printf "/%s/%s" ( $.Values.hostPathPrefix | replace "<APP_NAMESPACE>" $.Release.Namespace) $component.name }}
            type: DirectoryOrCreate
        {{ else }}
        - name: {{ $component.name }}
          persistentVolumeClaim:
            claimName: {{ printf "%s" $.Values.storage_name }}
        {{ end }}
        {{ end }}
        {{- if $component.extraVolumes -}}
          {{- range $volumeLabel, $volume := $component.extraVolumes }}
        -
            {{- toYaml $volume | nindent 10 }}
          {{- end }}
        {{- end }}
      {{- end }}
{{ end }}
{{ end }}