# Create an hpa for the md core deployment
{{- if $.Values.hpa.enabled -}}
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ $.Values.hpa.deployment | default "md-core"}}
spec:
  minReplicas: {{ $.Values.hpa.minReplicas }}
  maxReplicas: {{ $.Values.hpa.maxReplicas }}
  targetCPUUtilizationPercentage: {{ $.Values.hpa.cpuTargetUtilization }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name:  {{ $.Values.hpa.deployment | default "md-core" | quote }}
{{ end }}