{{ if .Values.core_ingress.enabled }}
---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: core-ingress
  annotations:
    {{ if not .Values.core_ingress.spec_className }}
    kubernetes.io/ingress.class: {{ .Values.core_ingress.class }}
    {{ end }}
    ingress.kubernetes.io/rewrite-target: /
    {{- if .Values.core_ingress.ingress_annotations }}
      {{- toYaml .Values.core_ingress.ingress_annotations | nindent 4 }}
    {{ end }}
    {{ if and (.Values.core_ingress.tls) (eq .Values.core_ingress.class "nginx") }}
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    {{ end }}

spec:
  {{ if .Values.core_ingress.spec_className }}
  ingressClassName: {{ .Values.core_ingress.class }}
  {{ end }}
  {{ if .Values.core_ingress.rules }}
  rules: 
    {{- toYaml .Values.core_ingress.rules | nindent 4 }}
  {{ else }}
  rules:
  - host: {{ .Values.core_ingress.host | replace "<APP_NAMESPACE>" .Release.Namespace }}
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: {{ .Values.core_ingress.service }}
              port:
                number: {{ .Values.core_ingress.port }}
  {{ end }}
  {{ if .Values.core_ingress.tls }}
  tls:
  - hosts:
    - {{ .Values.core_ingress.host | replace "<APP_NAMESPACE>" .Release.Namespace }}
    secretName: {{ .Values.core_ingress.secret }}
  {{ end }}
{{ end }}
