
# Create a service for each component in MD Core it has exposed ports
{{ range $component_name, $component := .Values.core_components }}
{{ if and $component.ports ( or (not $component.module_name) (contains (print $component.module_name) $.Values.ENABLED_MODULES)) }}
{{ if and (not $.Values.deploy_with_core_db) $component.is_db }}

{{ else }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $component.name | quote }}
  {{- if $component.service_annotations }}
  annotations:
    {{- toYaml $component.service_annotations | nindent 4 }}
  {{- end }}
spec:
{{- if $component.serviceSpec }}
  {{- toYaml $component.serviceSpec | nindent 2 }}
{{- else }}
  ports:
  {{- range $component.ports }}
    - name: {{ .port | quote }}
      port: {{ .port }}
      targetPort: {{ .port }}
  {{- end }}
  {{- if $component.service_type }}
  type: {{ $component.service_type }}
  {{- end }}
  {{- if $component.sessionAffinity }}
  sessionAffinity: {{ $component.sessionAffinity }}
  {{- end }}
  selector:
      app: {{ $component.name | quote }}
{{- end }}
status:
  loadBalancer: {}
{{ end }}

{{ end }}

{{ end }}