{{ if $.Values.storage_configs }}

{{ range $storage_name, $storage_value := .Values.storage_configs }}
---
{{- toYaml $storage_value }}

{{ end }}

{{ end }}

{{- if kindIs "slice" .Values.pvc }}
  # The value is a list
{{- range $i, $pvc := .Values.pvc }}
{{ if $pvc.enabled }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $pvc.name | quote }}
  labels:
    {{- range $k, $v := $pvc.labels }}
    {{ $k }}: {{ $v | quote }}
    {{- end }}
  annotations:
    {{- range $k, $v := $pvc.annotations }}
    {{ $k }}: {{ $v | quote }}
    {{- end }}
spec:
  accessModes:
    {{- range $mode := $pvc.accessModes }}
    - {{ $mode | quote }}
    {{- end }}
  resources:
    requests:
      storage: {{ $pvc.resources.requests.storage | quote }}
  storageClassName: {{ $pvc.storageClassName | quote }}
  volumeMode: {{ $pvc.volumeMode | quote }}

  {{- if $pvc.selector }}
  selector:
    matchLabels:
      {{- range $k, $v := $pvc.selector.matchLabels }}
      {{ $k }}: {{ $v | quote }}
      {{- end }}
  {{- end }}

  {{- if $pvc.volumeName }}
  volumeName: {{ $pvc.volumeName | quote }}
  {{- end }}

{{ end }}
{{- end }}

{{- else }}
  # The value is not a list
{{ if $.Values.pvc.enabled }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.pvc.name }}
  labels:
    {{- range $key, $value := .Values.pvc.labels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  annotations:
    {{- range $key, $value := .Values.pvc.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  accessModes:
    {{- range .Values.pvc.accessModes }}
    - {{ . | quote }}
    {{- end }}
  resources:
    requests:
      storage: {{ .Values.pvc.resources.requests.storage }}
  storageClassName: {{ .Values.pvc.storageClassName | quote }}
  volumeMode: {{ .Values.pvc.volumeMode | quote }}
  {{- if .Values.pvc.selector }}
  selector:
    matchLabels:
      {{- range $key, $value := .Values.pvc.selector.matchLabels }}
      {{ $key }}: {{ $value | quote }}
      {{- end }}
  {{- end }}
  {{- if .Values.pvc.volumeName }}
  volumeName: {{ .Values.pvc.volumeName | quote }}
  {{- end }}
{{ end }}

{{- end }}
