{{ if $.Values.auto_onboarding }}

{{- $onboardingSecret := (lookup "v1" "Secret" .Release.Namespace "onboarding-env") }}
---
kind: Secret
apiVersion: v1
metadata:
  name: onboarding-env
  annotations:
    "helm.sh/resource-policy": keep
data:
  {{ if $.Values.ONBOARDING_USER_NAME }}
  USER_NAME: {{ $.Values.ONBOARDING_USER_NAME | b64enc | quote }}
  {{ else if $onboardingSecret}}
  USER_NAME: {{ index $onboardingSecret.data "USER_NAME"  }} 
  {{ else }}
  USER_NAME: {{ "admin" | b64enc | quote }}
  {{ end }}
  {{ if $.Values.ONBOARDING_PASSWORD }}
  USER_PASSWORD: {{ $.Values.ONBOARDING_PASSWORD | b64enc | quote }}
  {{ else if $onboardingSecret}}
  USER_PASSWORD: {{ index $onboardingSecret.data "USER_PASSWORD" }}
  {{ else }}
  USER_PASSWORD: {{ (randAlphaNum 24) | nospace | b64enc | quote }}
  {{ end }}
  {{ if $.Values.ONBOARDING_EMAIL }}
  USER_EMAIL: {{ $.Values.ONBOARDING_EMAIL | b64enc | quote }}
  {{ else if $onboardingSecret}}
  USER_EMAIL: {{ index $onboardingSecret.data "USER_EMAIL" }}
  {{ else }}
  USER_EMAIL: {{ "admin@admin" | b64enc | quote }}
  {{ end }}
  {{ if $.Values.ONBOARDING_FULL_NAME }}
  USER_FULL_NAME: {{ $.Values.ONBOARDING_FULL_NAME | b64enc | quote }}
  {{ else if $onboardingSecret }}
  USER_FULL_NAME: {{ index $onboardingSecret.data "USER_FULL_NAME" }}
  {{ else }}
  USER_FULL_NAME: {{ "admin" | b64enc | quote }}
  {{ end }}

---
apiVersion: v1
kind: Secret
metadata:
  name: mdssc-import-config
data:
  {{ if $.Values.mdssc_import_config }}
  mdssc-config.json: |
    {{ .Values.mdssc_import_config | b64enc }}
  {{ else }}
  mdssc-config.json: |
    {{ "" | b64enc }}
  {{ end }}

{{ end }}

{{- if .Values.mdssc_generate_secrets}}

# Generate, set or keep the postgres database credentials for MDSSC
{{- $mdsscPostgresPasswordValue := (randAlphaNum 24) | nospace }}
{{- $mdsscPostgresUserValue := "mdssc" }}
{{- $mdsscPostgresSecret := (lookup "v1" "Secret" .Release.Namespace "mdssc-postgres-cred") }}

{{- if $mdsscPostgresSecret }}
{{- if index $mdsscPostgresSecret.data "POSTGRES_PASSWORD" }}
{{- $mdsscPostgresPasswordValue = index $mdsscPostgresSecret.data "POSTGRES_PASSWORD" | b64dec }}
{{- end }}
{{- if index $mdsscPostgresSecret.data "POSTGRES_USER" }}
{{- $mdsscPostgresUserValue = index $mdsscPostgresSecret.data "POSTGRES_USER" | b64dec }}
{{- end }}
{{- end -}}

{{- if .Values.MDSSC_DB_PASSWORD }}
{{- $mdsscPostgresPasswordValue = .Values.MDSSC_DB_PASSWORD }}
{{- end -}}

{{- if .Values.MDSSC_DB_USER }}
{{- $mdsscPostgresUserValue = .Values.MDSSC_DB_USER }}
{{- end }}

---
kind: Secret
apiVersion: v1
metadata:
  name: {{ .Values.mdssc_secret_env_name | default "mdssc-postgres-cred" }}
  annotations:
    "helm.sh/resource-policy": keep
data:
  POSTGRES_USER: {{ $mdsscPostgresUserValue | b64enc }}
  POSTGRES_PASSWORD: {{ $mdsscPostgresPasswordValue | b64enc }}
  POSTGRES_DB: {{ .Values.MDSSC_DB_NAME | default "MDSSC" | b64enc }}
  POSTGRESQL_URL: {{ (.Values.POSTGRESQL_URL | replace "<MDSSC_DB_HOST>" (.Values.MDSSC_DB_HOST | default "postgres-mdssc") | replace "<MDSSC_DB_PORT>" (.Values.MDSSC_DB_PORT | default "5432") | replace "<MDSSC_DB_USER>" ($mdsscPostgresUserValue) | replace "<MDSSC_DB_PASSWORD>" ($mdsscPostgresPasswordValue) | replace "<MDSSC_DB_NAME>" (.Values.MDSSC_DB_NAME | default "MDSSC")) | b64enc }}

{{ end }}