{{- if .Values.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: mdicapsrv-hpa
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: mdicapsrv
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.icap_components.md_icapsrv.name }}
  minReplicas: {{ .Values.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.maxReplicas }}
  metrics:
    {{- toYaml .Values.autoscaling.metrics | nindent 4}}
  behavior:
    {{- toYaml .Values.autoscaling.behavior | nindent 4}}
{{- end }}