{{ if .Values.icap_ingress.enabled }}
---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: icap-ingress
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.icap_ingress.class }}
    ingress.kubernetes.io/rewrite-target: /
  {{- if .Values.icap_components.md_icapsrv.tls.https.enabled }}
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
  {{- end }}
spec:
  rules:
  - host: {{ .Values.icap_ingress.host }} 
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: {{ .Values.icap_ingress.service }}
              port:
                number: {{ .Values.icap_ingress.rest_port }}
{{- if .Values.icap_components.md_icapsrv.tls.https.enabled }}
  tls:
    - hosts:
        - {{ .Values.icap_ingress.host }} 
      secretName: {{ .Values.icap_components.md_icapsrv.tls.https.certSecret }}
{{ end }}
{{ end }}

