{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: mdicapsrv-pdb
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: mdicapsrv
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      app: {{ .Values.icap_components.md_icapsrv.name | quote }}
{{- end }}
