kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: mdicapsrv-worker-role
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods","secrets"]
  verbs: ["create","update","get","list","patch"]
