---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.icap_components.md_icapsrv.custom_secret }}
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/resource-policy": keep
type: Opaque