{{- if .Values.storage_configs.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ printf "%s-pvc" .Values.storage_configs.storageClassName }}
  annotations:
    "helm.sh/resource-policy": keep
spec:
  accessModes:
    {{- toYaml .Values.storage_configs.accessModes | nindent 4}}
  resources:
    requests:
      storage: {{ .Values.storage_configs.resources.requests.storage }}
  storageClassName: {{ .Values.storage_configs.storageClassName }}
{{ end }}