
## Uncomment the following lines to set a fixed user and password for the MD Core web interface that will overwrite 
## any secret that already exists for these credentials (the secret will be kept when the chart is deleted)
## If left unset the following will apply:
## - if no "mdcore-cred" secret exists, it will be created with the user "admin" and a random password
## - if the "mdcore-cred" secret exists, the values from the secret are used as credentials

# mdcore_user: admin
# mdcore_password: <SET_PASSWORD_HERE>


## Uncomment the following lines to set a fixed user and password for the MD Core PostgreSQL database that will overwrite 
## any secret that already exists for these credentials (the secret will be kept when the chart is deleted)
## If left unset the following will apply:
## - if no "mdcore-postgres-cred" secret exists, it will be created with the user "postgres" and a random password
## - if the "mdcore-postgres-cred" secret exists, the values from the secret are used as credentials

db_user: postgres
db_password: <SET_CLOUD_SQL_PASSWORD_HERE>


## Uncomment the following line to set a fixed API key for MD Core that will overwrite 
## any secret that already exists for API key (the secret will be kept when the chart is deleted)
## If left unset the following will apply:
## - if no "mdcore-api-key" secret exists, it will be created with a random 36 character API key
## - if the "mdcore-api-key" secret exists, the value from the secret is used

# mdcore_api_key: <SET_36_CHARACTER_API_KEY>


## Set your MD Core license key here and it will be stored in the "mdcore-license-key" secret that will be created 
## if it does not exist. If left unset then a a secret is generated with and empty license key.

mdcore_license_key: <SET_LICENSE_KEY_HERE>

## MD Core settings that are saved in the "mdcore_env" config map
MDCORE_REST_PORT: "8008"
MDCORE_DB_MODE: "4"
MDCORE_DB_TYPE: remote
MDCORE_DB_HOST: 127.0.0.1
MDCORE_DB_PORT: "5432"
MDCORE_CERT_PATH: "/cert"

deploy_with_core_db: false
storage_provisioner: hostPath
## The host path on gcloud nodes has to be somewhere with read/write permissions
hostPathPrefix: /mnt/stateful_partition/opswat

# Set to false to not create any volumes or host paths in the deployment, all storage will be ephemeral
persistance_enabled: true

# # Set the service_type to LoadBalancer in order to create an external load balancer routing traffic directly to the web interface
core_components:
  md-core:
    name: md-core
    service_type: LoadBalancer
    replicas: 1
    initContainers: null
    sidecars:
      - name: activation-manager
        image: opswat/md-activation-manager
        envFrom:
          - configMapRef:
              name: mdcore-env
        env:
          - name: APIKEY
            valueFrom:
              secretKeyRef:
                name: mdcore-api-key
                key: value
          - name: LICENSE_KEY
            valueFrom:
              secretKeyRef:
                name: mdcore-license-key
                key: value
          - name: MDCORE_BASE_URL
            value: http://localhost
      - name: cloud-sql-proxy
        image: gcr.io/cloudsql-docker/gce-proxy:latest
        command:
          - "/cloud_sql_proxy"

          # If connecting from a VPC-native GKE cluster, you can use the
          # following flag to have the proxy connect over private IP
          # - "-ip_address_types=PRIVATE"
          - "-instances=<CLOUDSQL_CONNECTION_NAME>=tcp:5432"
        securityContext:
          # The default Cloud SQL proxy image runs as the
          # "nonroot" user and group (uid: 65532) by default.
          runAsNonRoot: true


# Ingress setting for mdss and md core
core_ingress:
  host: <APP_NAMESPACE>-mdcore.k8s
  class: gce
  enabled: false

# enable TLS
# md-core:
#   livenessProbe:
#     httpGet:
#       scheme: HTTPS
#   tls:
#     enabled: true

# Docker repo to use, this should be changed when using private images (this string will be prepended to the image name)
# If a component has "custom_repo: true" then the image name will be formated as "{docker_repo/}image_name{:BRANCH}" otherwise it will remain unaltered
core_docker_repo: opswat