---
spec:
  template:
    spec:
      containers:
        - name: <NGINX_CONTAINER_NAME>                                            # Container name within the Deployment/DaemonSet of the ingress controller
          image: opswat/nginx-ingress:controller-1.8.1_ometascan-1.1.0
