---
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Values.mdss_config_map_env_name }}
data:
  MONGO_URL: {{ .Values.MONGO_URL  | quote }}
  MONGO_SSL_ALLOW_INVALID_CERTIFICATES: {{ .Values.MONGO_SSL_ALLOW_INVALID_CERTIFICATES  | quote }}
  MONGO_CA_CERTIFICATE: {{ .Values.MONGO_CA_CERTIFICATE  | quote }}
  MONGO_DB: {{ .Values.MONGO_DB  | quote }}
  MONGO_MIGRATIONS_HOST: {{ .Values.MONGO_MIGRATIONS_HOST  | quote }}
  MONGO_MIGRATIONS_PORT: {{ .Values.MONGO_MIGRATIONS_PORT  | quote }}
  RABBITMQ_HOST: {{ .Values.RABBITMQ_HOST  | quote }}
  RABBITMQ_PORT: {{ .Values.RABBITMQ_PORT  | quote }}
  APIGATEWAY_PORT: {{ .Values.APIGATEWAY_PORT  | quote }}
  APIGATEWAY_PORT_SSL: {{ .Values.APIGATEWAY_PORT_SSL  | quote }}
  NGINX_TIMEOUT: {{ .Values.NGINX_TIMEOUT  | quote }}
  BACKUPS_TO_KEEP: {{ .Values.BACKUPS_TO_KEEP  | quote }}
  LICENSINGSERVICE_HOST: {{ .Values.LICENSINGSERVICE_HOST  | quote }}
  LICENSINGSERVICE_URL: {{ .Values.LICENSINGSERVICE_URL  | quote }}
  LICENSINGSERVICE_PORT: {{ .Values.LICENSINGSERVICE_PORT  | quote }}
  SMBSERVICE_URL: {{ .Values.SMBSERVICE_URL  | quote }}
  SMBSERVICE_PORT: {{ .Values.SMBSERVICE_PORT  | quote }}
  RABBITMQ_SCANNING_PREFETCH_COUNT: {{ .Values.RABBITMQ_SCANNING_PREFETCH_COUNT  | quote }}
  HTTPS_ACTIVE: {{ .Values.HTTPS_ACTIVE  | quote }}
  BRANCH: {{ .Values.BRANCH  | quote }}
  LOG_LEVEL: {{ .Values.LOG_LEVEL  | quote }}
  APP_LOG_LEVEL: {{ .Values.APP_LOG_LEVEL  | quote }}
  SMB_SHORT_DEADLINE: {{ .Values.SMB_SHORT_DEADLINE  | quote }}
  SMB_LONG_DEADLINE: {{ .Values.SMB_LONG_DEADLINE  | quote }}
  POLLY_RETRY_COUNT: {{ .Values.POLLY_RETRY_COUNT  | quote }}
  POLLY_LONG_RETRY: {{ .Values.POLLY_LONG_RETRY  | quote }}
  POLLY_SHORT_RETRY: {{ .Values.POLLY_SHORT_RETRY  | quote }}
  SMB_UPLOAD_CHUNK: {{ .Values.SMB_UPLOAD_CHUNK  | quote }}
  SMBSERVICE_FOLLOW_SYMLINKS: {{ .Values.SMBSERVICE_FOLLOW_SYMLINKS  | quote }}
  DISCOVERY_SERVICE_PERFORMANCE_OPTIMIZATION: {{ .Values.DISCOVERY_SERVICE_PERFORMANCE_OPTIMIZATION  | quote }}
  DISCOVERY_SERVICE_DEGREE_OF_PARALLELISM: {{ .Values.DISCOVERY_SERVICE_DEGREE_OF_PARALLELISM  | quote }}
  DISCOVERY_SERVICE_SMB_RTP_PROCESS_HANDLING: {{ .Values.DISCOVERY_SERVICE_SMB_RTP_PROCESS_HANDLING  | quote }}
  MD_CORE_CERTIFICATE_VALIDATION: {{ .Values.MD_CORE_CERTIFICATE_VALIDATION  | quote }}
  POLLY_LONG_RETRY_BOX: {{ .Values.POLLY_LONG_RETRY_BOX  | quote }}
  POLLY_SHORT_RETRY_BOX: {{ .Values.POLLY_SHORT_RETRY_BOX  | quote }}
  POLLY_POST_ACTION_RETRY_TIME: {{ .Values.POLLY_POST_ACTION_RETRY_TIME  | quote }}
  LOAD_BALANCER_MD_CORE_UNAVAILABLE_TIME: {{ .Values.LOAD_BALANCER_MD_CORE_UNAVAILABLE_TIME  | quote }}
  WEBCLIENT_HOST: {{ .Values.WEBCLIENT_HOST  | quote }}
  AZURE_BLOBS_PAGE_SIZE: {{ .Values.AZURE_BLOBS_PAGE_SIZE  | quote }}
  DISCOVERY_SERVICE_IGNORE_EMPTY_OBJECTS: {{ .Values.DISCOVERY_SERVICE_IGNORE_EMPTY_OBJECTS  | quote }}
  SMBSERVICE_DISCOVERY_DEBOUNCE_TIME: {{ .Values.SMBSERVICE_DISCOVERY_DEBOUNCE_TIME  | quote }}
  DISCOVERY_SERVICE_REPROCESSING_FAILED_TIME_HOURS: {{ .Values.DISCOVERY_SERVICE_REPROCESSING_FAILED_TIME_HOURS  | quote }}
  CACHE_SERVICE_URL: {{ .Values.CACHE_SERVICE_URL  | quote }}
  CACHE_SERVICE_PORT: {{ .Values.CACHE_SERVICE_PORT  | quote }}
  POLLY_RETRY_TIME: {{ .Values.POLLY_RETRY_TIME  | quote }}
  DOTNET_HOSTBUILDER__RELOADCONFIGONCHANGE: {{ .Values.DOTNET_HOSTBUILDER__RELOADCONFIGONCHANGE  | quote }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: webclient-nginx-config
data:
  default.conf: |
    server {
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name _;
    #return 301 https://$host$request_uri;
    
    add_header Referrer-Policy "no-referrer";
    add_header X-Content-Type-Options "nosniff";
    
    location / {
        try_files $uri $uri/ /index.html;
        root   /usr/share/nginx/html;
        index  index.html index.htm;
    }

    location /api {
        proxy_pass http://apigateway;
    }

    location /hubs { 
        proxy_pass http://apigateway;
        
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_http_version 1.1;
    }

    }
    server {
        #listen 443 ssl;
        #ssl_certificate /etc/nginx/conf.d/ssl.crt;
        #ssl_certificate_key /etc/nginx/conf.d/ssl.key;
        #ssl_protocols TLSv1.2 TLSv1.3;
        #ssl_ciphers 'ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384';
        #ssl_prefer_server_ciphers on;
        
        add_header X-Content-Type-Options "nosniff";
        add_header Referrer-Policy "no-referrer";
        add_header Strict-Transport-Security "max-age=15724800; includeSubdomains;";
        
        location / {
            try_files $uri $uri/ /index.html;
            root   /usr/share/nginx/html;
            index  index.html index.htm;
        }

        location /api {
            proxy_pass http://apigateway;
        }

        location /hubs { 
            proxy_pass http://apigateway;
            
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_http_version 1.1;
        }
    }

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: systemchecks-nginx-config
data:
  default.conf: |
    server {
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name _;
    #return 301 https://$host$request_uri;
    
    add_header Referrer-Policy "no-referrer";
    add_header X-Content-Type-Options "nosniff";

    location / {
        try_files $uri $uri/ /index.html;
        root   /usr/share/nginx/html;
        index  index.html index.htm;
    }

    location /api {
        proxy_pass http://127.0.0.1:5000/api;
    }

    location /status {
      rewrite ^/status(.*) /$1 break;
      proxy_pass         http://127.0.0.1:80/status;
      proxy_set_header   Host $http_host;
      proxy_set_header   X-Real-IP $remote_addr;
    }

    }
    server {
        #listen 443 ssl;
        #ssl_certificate /etc/nginx/conf.d/ssl.crt;
        #ssl_certificate_key /etc/nginx/conf.d/ssl.key;
        #ssl_protocols TLSv1.2 TLSv1.3;
        #ssl_ciphers 'ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384';
        #ssl_prefer_server_ciphers on;
        
        add_header X-Content-Type-Options "nosniff";
        add_header Referrer-Policy "no-referrer";
        add_header Strict-Transport-Security "max-age=15724800; includeSubdomains;";
        
        location / {
            try_files $uri $uri/ /index.html;
            root   /usr/share/nginx/html;
            index  index.html index.htm;
        }

        location /api {
            proxy_pass http://127.0.0.1:5000/api;
        }

        location /status {
            rewrite ^/status(.*) /$1 break;
            proxy_pass         http://127.0.0.1:80/status;
            proxy_set_header   Host $http_host;
            proxy_set_header   X-Real-IP $remote_addr;
        }

    }
