
# Create a deployment for each component in MDSS
{{ range $component_name, $component := .Values.mdss_components }}

{{ if and (or $.Values.deploy_with_mdss_db (not $component.is_db)) ( or (not $component.module_name) (contains (print $component.module_name) (index $.Values "mdss-common-environment").ENABLED_MODULES))  }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $component.name | quote }}
spec:
  replicas: {{ $component.replicas }}
  selector:
    matchLabels:
      app: {{ $component.name | quote }}
  strategy: {}
  template:
    metadata:
      labels:
        app: {{ $component.name | quote }}
        {{- if $component.extra_labels }}
          {{- toYaml $component.extra_labels | nindent 8 }}
        {{- end }}
    spec:
      containers:
        - envFrom:
            - configMapRef:
                name: {{ $.Values.mdss_config_map_env_name | quote }}
          {{- if $component.env }}
          env:
            {{- toYaml $component.env | nindent 12 }}
          {{- end }}
          {{- if $component.custom_repo }}
          image: {{ printf "%s/%s:%s" $.Values.mdss_docker_repo $component.image (index $.Values "mdss-common-environment").BRANCH | quote }}
          {{- else }}
          image: {{ $component.image | quote }}
          {{- end }}
          imagePullPolicy: {{ $.Values.imagePullPolicy }}
          name: {{ $component.name | quote }}
          {{- if $component.ports }}
          ports:
          {{- range $component.ports }}
            - containerPort: {{ .port }}
          {{- end }}
          {{- end }}
          {{- if $component.command }}
          command: 
            {{- toYaml $component.command | nindent 12 }}
          {{- end }}
          {{- if $component.args }}
          args:
            {{- toYaml $component.args | nindent 12 }}
          {{- end }}
          {{- if $component.securityContext }}
          securityContext:
            {{- toYaml $component.securityContext | nindent 12 }}
          {{- end }}
          {{- if (or $component.mountConfig (and $component.persistentDir $.Values.persistance_enabled) $component.customMounts)}}
          volumeMounts:
            {{- if $component.mountConfig }}
            - name: {{ $component.mountConfig.configName }}
              mountPath: {{ $component.mountConfig.mountPath }}
              subPath: {{ $component.mountConfig.subPath }}
            {{ end }}
            {{- if $component.persistentDir }}
            - name: {{ $component.name }}
              mountPath: {{ $component.persistentDir }}
              {{- if not (eq $.Values.storage_provisioner "hostPath") }}
              subPath: {{ $component.name }}
              {{- end }}
            {{ end }}
            {{- if $component.customMounts }}
              {{- toYaml $component.customMounts | nindent 12 }}
            {{- end }}
          {{- end }}
          {{- if $component.resources }}
          resources:
            {{- toYaml $component.resources | nindent 12 }}
          {{- end }}
          {{- if $component.update_ca }}
          lifecycle:
            postStart:
              exec:
                command: ["/bin/sh", "-c", "update-ca-certificates"]
          {{- end}}
      restartPolicy: Always
      {{- if $.Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml $.Values.imagePullSecrets | nindent 8 }}
      {{- end }}
      imagePullPolicy: {{ $.Values.imagePullPolicy }}
      {{- if $component.nodeSelector }}
      nodeSelector:
        {{- toYaml $component.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if (or $component.mountConfig (and $component.persistentDir $.Values.persistance_enabled) $component.customVolumes)}}
      volumes:
        {{- if $component.mountConfig }}
        - name: {{ $component.mountConfig.configName }}
          configMap:
            name: {{ $component.mountConfig.configName }}
        {{ end }}
        {{- if (and $component.persistentDir $.Values.persistance_enabled) }}
        {{- if eq $.Values.storage_provisioner "hostPath" }}
        - name: {{ $component.name }}
          hostPath:
            path: {{ printf "/%s/%s" ( $.Values.hostPathPrefix | replace "<APP_NAMESPACE>" $.Release.Namespace) $component.name }}
            type: DirectoryOrCreate
        {{ else }}
        - name: {{ $component.name }}
          persistentVolumeClaim:
            claimName: {{ printf "%s-pvc" $.Values.storage_name }}
        {{- end }}
        {{- end }}
        {{- if $component.customVolumes }}
          {{- toYaml $component.customVolumes | nindent 8 }}
        {{- end }}
      {{- end }}
      hostAliases:
        {{- toYaml $.Values.mdssHostAliases | nindent 8 }}
      
{{ end }}
{{ end }}
