{{ if .Values.mdss_ingress.enabled }}
---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: webclient-ingress
  annotations:
    kubernetes.io/ingress.class: {{ .Values.mdss_ingress.class }}
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: {{ .Values.mdss_ingress.host | replace "<APP_NAMESPACE>" .Release.Namespace }}
    http:
      paths:
        - path: /status
          pathType: Prefix
          backend:
            service:
              name: {{.Values.mdss_components.systemchecks.name }}
              port:
                number: {{ .Values.mdss_ingress.port }}
        - path: /
          pathType: Prefix
          backend:
            service:
              name: {{ .Values.mdss_ingress.service }}
              port:
                number: {{ .Values.mdss_ingress.port }}

{{ end }}