{{ if $.Values.auto_onboarding }}

apiVersion: batch/v1
kind: Job
metadata:
  name: auto-onboarding
  namespace: {{ .Values.app_name }}
spec:
  template:
    metadata:
      labels:
        app: auto-onboarding
        aws-type: fargate
    spec:
      containers:
        - name: auto-onboarding
          image: {{ printf "%s/mdcloudservices_auto-onboarding:%s" $.Values.mdss_docker_repo $.Values.BRANCH | quote }}
          envFrom:
            - configMapRef:
                name: {{ $.Values.mdss_config_map_env_name | quote }}
            - secretRef:
                name: onboarding-env
          env:
            - name: ONBOARDING_CONFIG_FILE_NAME
              value: mdss-config.json
          volumeMounts:
            - name: mdss-import-config
              mountPath: /onboarding_settings/mdss-config.json
              subPath: mdss-config.json
      restartPolicy: OnFailure
      {{- if $.Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml $.Values.imagePullSecrets | nindent 8 }}
      {{- end }}
      volumes:
        - name: mdss-import-config
          secret:
            secretName: mdss-import-config

{{ end }}