{{ if $.Values.auto_onboarding }}

{{- $onboardingSecret := (lookup "v1" "Secret" .Release.Namespace "onboarding-env") }}
---
kind: Secret
apiVersion: v1
metadata:
  name: onboarding-env
  annotations:
    "helm.sh/resource-policy": keep
data:
  {{ if $.Values.ONBOARDING_USER_NAME }}
  USER_NAME: {{ $.Values.ONBOARDING_USER_NAME | b64enc | quote }}
  {{ else if $onboardingSecret}}
  USER_NAME: {{ index $onboardingSecret.data "USER_NAME"  }} 
  {{ else }}
  USER_NAME: {{ "admin" | b64enc | quote }}
  {{ end }}
  {{ if $.Values.ONBOARDING_PASSWORD }}
  USER_PASSWORD: {{ $.Values.ONBOARDING_PASSWORD | b64enc | quote }}
  {{ else if $onboardingSecret}}
  USER_PASSWORD: {{ index $onboardingSecret.data "USER_PASSWORD" }}
  {{ else }}
  USER_PASSWORD: {{ (randAlphaNum 24) | nospace | b64enc | quote }}
  {{ end }}
  {{ if $.Values.ONBOARDING_EMAIL }}
  USER_EMAIL: {{ $.Values.ONBOARDING_EMAIL | b64enc | quote }}
  {{ else if $onboardingSecret}}
  USER_EMAIL: {{ index $onboardingSecret.data "USER_EMAIL" }}
  {{ else }}
  USER_EMAIL: {{ "admin@admin" | b64enc | quote }}
  {{ end }}
  {{ if $.Values.ONBOARDING_FULL_NAME }}
  USER_FULL_NAME: {{ $.Values.ONBOARDING_FULL_NAME | b64enc | quote }}
  {{ else if $onboardingSecret }}
  USER_FULL_NAME: {{ index $onboardingSecret.data "USER_FULL_NAME" }}
  {{ else }}
  USER_FULL_NAME: {{ "admin" | b64enc | quote }}
  {{ end }}

---
apiVersion: v1
kind: Secret
metadata:
  name: mdss-import-config
data:
  {{ if $.Values.mdss_import_config }}
  mdss-config.json: |
    {{ .Values.mdss_import_config | b64enc }}
  {{ else }}
  mdss-config.json: |
    {{ "" | b64enc }}
  {{ end }}

{{ end }}