# project_id = "metadefender-k8s"
# region = "europe-central2"
# cluster_location = "europe-central2-a"
gcloud_json_key_path = "/path/to/json"
# node_count = "1"
# machine_type = "e2-standard-8"
# deploy_cloud_sql = true
# private_ip_cloud_sql = true
# cloud_sql_user = postgres
# cloud_sql_password = mdcorepostgres