# project_id = "<ADD_YOUR_PROJECT_ID>"
# region = "europe-central2"
gcloud_json_key_path = "/path/to/json"
# node_count = "1"
# machine_type = "e2-standard-8"
deploy_cloud_sql = true
AUTOPILOT_GKE = false
# private_ip_cloud_sql = true
# cloud_sql_user = postgres
# cloud_sql_password = <ADD_YOUR_POSTGRES_PASS>
